name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Firebase login
        run: firebase login --no-localhost

      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --project super-notes-ed64f
